services:
  webtaller:
    build:
      context: .. 
      dockerfile: ./deploy/Dockerfile
    container_name: ptaller
    image: youssefmf/ubptaller
    volumes:
      - ./logs:/root/logs
    ports:
      - "8830:80"



