apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: miportfolio
  annotations: {}
spec:
  rules:
    - host: webtaller.youssefmfitah.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webtaller-service
                port:
                  number: 80